"""Project the bashOS registry onto the engine as `opencode.jsonc`.

`.claude/commands/*.md` stays the single source of truth. This module compiles
it into the one thing the engine reads — a generated project config carrying:

  * the two bashOS agents and the tool policy each one runs under, and
  * every registry command as an OpenCode command.

So one markdown file is now three runtimes: a Claude Code slash command, a
bashOS kernel program, and an OpenCode command. The config is generated, not
authored — `bashos opencode sync` writes it and a test fails if it drifts.

The restrictive policy is attached to the bashOS *agents*, never to the
project's global `permission` block: a developer running plain `opencode` in
this repository keeps their normal tools, while anything the bashOS kernel
dispatches is bound by policy.py.

The generated file is a function of the registry and the *defaults* only —
never of a per-invocation flag. `bashos run -m other-model` must not rewrite a
committed file as a side effect, so runtime overrides are passed to the engine
API per request instead.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..config import DEFAULT_MODEL, KernelConfig
from ..kernel.context import HOUSE_SYSTEM
from ..registry import CommandSpec
from . import policy

CONFIG_FILE = "opencode.jsonc"
SCHEMA_URL = "https://opencode.ai/config.json"
DEFAULT_PROVIDER = "anthropic"

READONLY_AGENT = "bashos"
SEALED_AGENT = "bashos-sealed"

# Which agent — and therefore which tool policy — each orchestration loop runs
# under. A command may override with `bashos: {agent: ...}`.
LOOP_AGENTS = {
    "prompt": SEALED_AGENT,
    "refine": SEALED_AGENT,
    "react": READONLY_AGENT,
}

HEADER = (
    "// generated by `bashos opencode sync` — do not edit.\n"
    "// source of truth: .claude/commands/*.md and src/bashos/opencode/policy.py\n"
)

_READONLY_NOTE = """\

You are running as a bashOS inspection agent. Your tools are read-only by
policy: file reads and searches are allowed, `bash` is restricted to an
allowlist of diagnostic probes, and every mutating or outbound tool is denied.
Do not attempt work outside that boundary — report what you find instead."""

_SEALED_NOTE = """\

You have no tools in this context — answer directly in a single message."""


def qualify_model(model: str, provider: str = DEFAULT_PROVIDER) -> str:
    """`claude-opus-5` → `anthropic/claude-opus-5`; qualified ids pass through."""
    return model if "/" in model else f"{provider}/{model}"


def agent_for(spec: CommandSpec) -> str:
    return spec.agent or LOOP_AGENTS.get(spec.loop, SEALED_AGENT)


def build_agents(model: str, max_steps: int) -> dict[str, dict[str, object]]:
    return {
        READONLY_AGENT: {
            "description": "bashOS inspection agent — read-only probes on the real machine",
            "mode": "primary",
            "model": qualify_model(model),
            "prompt": HOUSE_SYSTEM + _READONLY_NOTE,
            "maxSteps": max_steps,
            "tools": policy.readonly_tools(),
            "permission": policy.readonly_permission(),
        },
        SEALED_AGENT: {
            "description": "bashOS completion agent — no tools, one answer",
            "mode": "primary",
            "hidden": True,
            "model": qualify_model(model),
            "prompt": HOUSE_SYSTEM + _SEALED_NOTE,
            "tools": policy.sealed_tools(),
            "permission": policy.sealed_permission(),
        },
    }


def build_commands(registry: dict[str, CommandSpec]) -> dict[str, dict[str, object]]:
    commands: dict[str, dict[str, object]] = {}
    for name, spec in sorted(registry.items()):
        entry: dict[str, object] = {
            "template": spec.body,
            "agent": agent_for(spec),
        }
        if spec.description:
            entry["description"] = spec.description
        commands[name] = entry
    return commands


def build_config(
    registry: dict[str, CommandSpec],
    model: str = DEFAULT_MODEL,
    max_steps: int | None = None,
) -> dict[str, object]:
    steps = KernelConfig().react_max_turns if max_steps is None else max_steps
    return {
        "$schema": SCHEMA_URL,
        "model": qualify_model(model),
        "agent": build_agents(model, steps),
        "command": build_commands(registry),
    }


def render_config(registry: dict[str, CommandSpec], model: str = DEFAULT_MODEL) -> str:
    # ensure_ascii=False keeps the prompts readable — this file gets reviewed
    body = json.dumps(
        build_config(registry, model), indent=2, sort_keys=False, ensure_ascii=False
    )
    return f"{HEADER}{body}\n"


def config_path(root: Path) -> Path:
    return root / CONFIG_FILE


def sync(root: Path, registry: dict[str, CommandSpec]) -> tuple[Path, bool]:
    """Write the generated config. Returns (path, changed)."""
    path = config_path(root)
    rendered = render_config(registry)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == rendered:
        return path, False
    path.write_text(rendered, encoding="utf-8")
    return path, True


def is_in_sync(root: Path, registry: dict[str, CommandSpec]) -> bool:
    path = config_path(root)
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8") == render_config(registry)
